namespace Certify.Core.Localization;

/// <summary>
/// Centralna tabela stringow UI. PL/EN sa tutaj (zrodlo prawdy), pozostale jezyki
/// w osadzonych plikach Localization/Translations/&lt;kod&gt;.json (klucz -> tekst,
/// brakujacy klucz -> angielski). XAML uzywa kluczy przez DynamicResource
/// (slownik budowany w runtime), kod przez T(). Logi techniczne celowo po polsku.
/// </summary>
public static class UIStrings
{
    public static string Lang { get; set; } = "pl";

    /// <summary>
    /// Obslugiwane jezyki (kod ISO 639-1, nazwa natywna): 20 najpopularniejszych
    /// jezykow tresci w internecie (ranking W3Techs), w tym polski.
    /// </summary>
    public static IReadOnlyList<(string Code, string Name)> Languages { get; } =
    [
        ("en", "English"),
        ("pl", "Polski"),
        ("de", "Deutsch"),
        ("es", "Español"),
        ("fr", "Français"),
        ("it", "Italiano"),
        ("pt", "Português"),
        ("nl", "Nederlands"),
        ("cs", "Čeština"),
        ("hu", "Magyar"),
        ("tr", "Türkçe"),
        ("ru", "Русский"),
        ("uk", "Українська"),
        ("ar", "العربية"),
        ("fa", "فارسی"),
        ("zh", "中文（简体）"),
        ("ja", "日本語"),
        ("ko", "한국어"),
        ("vi", "Tiếng Việt"),
        ("id", "Bahasa Indonesia"),
    ];

    public static bool IsSupported(string? code) => code != null && Languages.Any(l => l.Code == code);

    public static bool IsRightToLeft(string lang) => lang is "ar" or "fa";

    /// <summary>Auto -> jezyk systemu, jesli obslugiwany (inaczej en); reczny wybor wprost.</summary>
    public static string ResolveLang(string setting, string osTwoLetter)
    {
        if (IsSupported(setting)) return setting;
        return IsSupported(osTwoLetter) ? osTwoLetter : "en";
    }

    public static IEnumerable<string> Keys => S.Keys;

    public static bool Has(string key) => S.ContainsKey(key);

    public static string T(string key, params object?[] args)
    {
        if (!S.TryGetValue(key, out var pair)) return key;
        var template = Lang switch
        {
            "pl" => pair.Pl,
            "en" => pair.En,
            _ => Translation(Lang).GetValueOrDefault(key) ?? pair.En,
        };
        if (string.IsNullOrEmpty(template) && Lang != "pl") template = pair.Pl; // fallback
        try
        {
            return args.Length == 0 ? template : string.Format(System.Globalization.CultureInfo.InvariantCulture, template, args);
        }
        catch { return template; }
    }

    private static readonly System.Collections.Concurrent.ConcurrentDictionary<string, IReadOnlyDictionary<string, string>> Translations = new();

    /// <summary>Tlumaczenia jezyka spoza PL/EN (pusty slownik, gdy brak pliku).</summary>
    public static IReadOnlyDictionary<string, string> Translation(string lang) =>
        Translations.GetOrAdd(lang, static l =>
        {
            using var stream = typeof(UIStrings).Assembly.GetManifestResourceStream($"Certify.Core.Localization.Translations.{l}.json");
            if (stream == null) return new Dictionary<string, string>();
            return System.Text.Json.JsonSerializer.Deserialize<Dictionary<string, string>>(stream) ?? new Dictionary<string, string>();
        });

    private static readonly Dictionary<string, (string Pl, string En)> S = new()
    {
        // ---- wspolne ----
        ["Btn_Cancel"] = ("Anuluj", "Cancel"),
        ["Btn_Save"] = ("Zapisz", "Save"),
        ["Btn_Close"] = ("Zamknij", "Close"),
        ["Btn_Edit"] = ("Edytuj", "Edit"),
        ["Btn_Delete"] = ("Usuń", "Delete"),
        ["Dlg_ConfirmTitle"] = ("Potwierdź", "Confirm"),
        ["Msg_SelectCert"] = ("Wybierz certyfikat", "Select a certificate"),

        // ---- Main ----
        ["Win_Main_Title"] = ("CertifyApp - menedżer certyfikatów ACME", "CertifyApp - ACME certificate manager"),
        ["Main_Side_Tagline"] = ("Certyfikaty ACME dla IIS, Apache i Nginx", "ACME certificates for IIS, Apache and Nginx"),
        ["Main_Nav_Manage"] = ("ZARZĄDZANIE", "MANAGE"),
        ["Main_Nav_Certs"] = ("Certyfikaty", "Certificates"),
        ["Main_Nav_Count"] = ("{0} certyfikatów", "{0} certificates"),
        ["Main_Side_DataSub"] = ("Katalog danych", "Data directory"),
        ["Main_Btn_OpenFolder"] = ("Otwórz folder", "Open folder"),
        ["Main_Top_Title"] = ("Certyfikaty", "Certificates"),
        ["Main_Btn_Refresh"] = ("Odśwież", "Refresh"),
        ["Main_Btn_TaskSched"] = ("Harmonogram", "Task Scheduler"),
        ["Main_Tip_TaskSched"] = ("Dodaje zadanie Harmonogramu zadań: codzienne odnawianie o 03:00", "Adds a Task Scheduler job: daily renewal at 03:00"),
        ["Main_Btn_Service"] = ("Usługa Windows", "Windows service"),
        ["Main_Tip_Service"] = ("Odnawianie w tle jako usługa Windows, także przy zamkniętej aplikacji", "Background renewal as a Windows service, also while the app is closed"),
        ["Main_Btn_Settings"] = ("Ustawienia", "Settings"),
        ["Main_Tip_Settings"] = ("Język i powiadomienia e-mail", "Language and e-mail notifications"),
        ["Main_Btn_Calendar"] = ("Kalendarz", "Calendar"),
        ["Main_Tip_Calendar"] = ("Kalendarz odnowień i wygasań", "Renewal and expiry calendar"),
        ["Main_Btn_RenewAll"] = ("Odnów wymagające", "Renew due"),
        ["Main_Btn_New"] = ("+ Nowy certyfikat", "+ New certificate"),
        ["Main_Btn_Request"] = ("Wystaw / odnów", "Request / Renew"),
        ["Main_Btn_Staging"] = ("Test (staging)", "Test (staging)"),
        ["Main_Btn_Deploy"] = ("Wdróż", "Deploy"),
        ["Main_Btn_Export"] = ("Eksportuj", "Export"),
        ["Main_Tip_Export"] = ("Eksport do PEM / PFX", "Export to PEM / PFX"),
        ["Main_Btn_Preview"] = ("Podgląd", "Preview"),
        ["Main_Tip_Preview"] = ("Podgląd i sprawdzenie konfiguracji przed wystawieniem", "Preview and validate the configuration before requesting"),
        ["Main_Btn_Backup"] = ("Kopia zapasowa", "Backup"),
        ["Main_Tip_Backup"] = ("Kopia certyfikatów, kont ACME i ustawień (.cbak szyfrowany lub .zip)", "Backup of certificates, ACME accounts and settings (encrypted .cbak or .zip)"),
        ["Main_Btn_Import"] = ("Importuj", "Import"),
        ["Main_Btn_Details"] = ("Szczegóły", "Details"),
        ["Main_Filter_Backup"] = ("Szyfrowany backup (*.cbak)|*.cbak|Backup (*.zip)|*.zip",
            "Encrypted backup (*.cbak)|*.cbak|Backup (*.zip)|*.zip"),
        ["Main_Tip_Import"] = ("Przywróć z kopii zapasowej (połącz lub zastąp)", "Restore from backup (merge or replace)"),
        ["Main_Status_Ready"] = ("Gotowy", "Ready"),
        ["Main_Op_Elapsed"] = ("{0}... ({1} s)", "{0}... ({1} s)"),
        ["Main_Op_Busy"] = ("Operacja w toku: {0}. Anuluj ją lub poczekaj.", "Operation in progress: {0}. Cancel it or wait."),
        ["Main_Op_Aborted"] = ("przerwano", "aborted"),
        ["Main_Grid_Title"] = ("CERTYFIKATY", "CERTIFICATES"),
        ["Main_Grid_Hint"] = ("Kliknij dwukrotnie wiersz, aby edytować", "Double-click a row to edit"),
        ["Grid_Name"] = ("NAZWA", "NAME"),
        ["Grid_Domains"] = ("DOMENY", "DOMAINS"),
        ["Grid_Status"] = ("STATUS", "STATUS"),
        ["Grid_Expires"] = ("WYGASA", "EXPIRES"),
        ["Grid_Days"] = ("DNI", "DAYS"),
        ["Grid_Message"] = ("WIADOMOŚĆ", "MESSAGE"),
        ["Main_Panel_Title"] = ("SZCZEGÓŁY", "DETAILS"),
        ["Main_Panel_NoSel"] = ("Wybierz certyfikat", "Select a certificate"),
        ["Main_Row_AutoRenew"] = ("Auto odnawianie:", "Auto renewal:"),
        ["Main_Row_LastRenewal"] = ("Ostatnie odnowienie:", "Last renewal:"),
        ["Main_Row_Expiry"] = ("Wygasa:", "Expires:"),
        ["Main_Row_NextRenewal"] = ("Następne odnowienie:", "Next renewal:"),
        ["Main_Row_LastCa"] = ("Urząd (CA):", "Authority (CA):"),
        ["Main_Row_Lifetime"] = ("Wykorzystanie czasu życia", "Lifetime used"),
        ["Main_Btn_OpenLog"] = ("Otwórz log", "Open log"),
        ["Main_Btn_History"] = ("Historia", "History"),
        ["Main_Tip_History"] = ("Historia operacji certyfikatu", "Certificate operation history"),
        ["Main_Log_Title"] = ("LOG", "LOG"),
        ["Main_Btn_Clear"] = ("Wyczyść", "Clear"),
        ["Main_Btn_SaveLog"] = ("Zapisz do pliku", "Save to file"),
        ["Main_Filter_Log"] = ("Plik tekstowy (*.txt)|*.txt|Wszystkie pliki (*.*)|*.*", "Text file (*.txt)|*.txt|All files (*.*)|*.*"),
        ["Main_Msg_LogSaveFailed"] = ("Nie udało się zapisać logu: {0}", "Failed to save the log: {0}"),
        ["Main_Loaded"] = ("Certyfikatów: {0}", "Certificates: {0}"),
        ["Main_Msg_DeleteConfirm"] = ("Usunąć {0}?", "Delete {0}?"),
        ["Main_Msg_SettingsSaved"] = ("Zapisano ustawienia.", "Settings saved."),
        ["Main_Msg_NewCert"] = ("Nowy certyfikat", "New certificate"),
        ["Main_Msg_NoCertIssued"] = ("Brak wystawionego certyfikatu - najpierw użyj Wystaw / odnów.", "No issued certificate - use Request / Renew first."),
        ["Main_Msg_DeleteConfirm"] = ("Usunąć {0}?", "Delete {0}?"),
        ["Badge_Active"] = ("✓ Certyfikat aktywny", "✓ Certificate active"),
        ["Badge_Expired"] = ("✕ Wygasł", "✕ Expired"),
        ["Badge_Error"] = ("! Błąd", "! Error"),
        ["Badge_Pending"] = ("… Oczekuje", "… Pending"),
        ["Badge_Revoked"] = ("✕ Unieważniony", "✕ Revoked"),
        ["Badge_NotStarted"] = ("○ Niewystawiony", "○ Not issued"),
        ["Yes"] = ("Tak", "Yes"),
        ["No"] = ("Nie", "No"),
        ["Main_ExpiryIn"] = ("{0} (za {1} dni)", "{0} (in {1} days)"),
        ["Pw_Prompt_Encrypt"] = ("Hasło do zaszyfrowania backupu.", "Password to encrypt the backup."),
        ["Pw_Prompt_Decrypt"] = ("Backup szyfrowany - podaj hasło.", "Encrypted backup - enter password."),

        // ---- edycja certyfikatu ----
        ["Win_Edit_Title"] = ("Edycja certyfikatu", "Edit certificate"),
        ["Edit_Header_Title"] = ("Konfiguracja certyfikatu", "Certificate configuration"),
        ["Edit_Header_Sub"] = ("Pierwsza domena to Common Name, wszystkie trafiają do SAN.", "The first domain is the Common Name, all of them go to SAN."),
        ["Edit_Sec_Basic"] = ("PODSTAWOWE", "BASIC"),
        ["Edit_Name"] = ("Nazwa", "Name"),
        ["Edit_Ca_Settings"] = ("USTAWIENIA URZĘDU (CA)", "CERTIFICATE AUTHORITY SETTINGS"),
        ["Edit_Custom_Hint"] = ("Pełny Directory URL serwera ACME (np. https://ca.example.com/directory)",
            "Full ACME server Directory URL (e.g. https://ca.example.com/directory)"),
        ["Edit_Sec_Domains"] = ("DOMENY - JEDNA W WIERSZU", "DOMAINS - ONE PER LINE"),
        ["Edit_Domains_Hint"] = ("Domena, *.domena (tylko DNS-01) lub adres IP (tylko Let's Encrypt)", "Domain, *.domain (DNS-01 only) or IP address (Let's Encrypt only)"),
        ["Edit_Btn_GetIis"] = ("Pobierz z IIS", "Get from IIS"),
        ["Edit_Tip_GetIis"] = ("Dopisz hostnames z bindingów site do listy domen i ustaw WebRoot na ścieżkę fizyczną site", "Append the site binding hostnames to the domain list and set WebRoot to the site physical path"),
        ["Edit_Lbl_Service"] = ("Usługa (restart)", "Service (restart)"),
        ["Edit_Tip_Service"] = ("Nazwa usługi Windows restartowanej po wdrożeniu (np. Apache2.4). Puste = wykryj automatycznie; Nginx bez usługi: nginx -s reload.", "Name of the Windows service restarted after deployment (e.g. Apache2.4). Empty = detect automatically; Nginx without a service: nginx -s reload."),
        ["Edit_Msg_WebrootSet"] = ("WebRoot ustawiony na ścieżkę fizyczną site '{0}':\n{1}", "WebRoot set to the physical path of site '{0}':\n{1}"),
        ["Edit_Sec_Http"] = ("WALIDACJA HTTP-01", "HTTP-01 VALIDATION"),
        ["Edit_Http_Hint"] = ("Plik walidacyjny trafia do <WebRoot>\\.well-known\\acme-challenge\\ - domena musi wskazywać na ten serwer (port 80).", "The validation file goes to <WebRoot>\\.well-known\\acme-challenge\\ - the domain must point to this server (port 80)."),
        ["Edit_Sec_Dns"] = ("WALIDACJA DNS-01", "DNS-01 VALIDATION"),
        ["Edit_Dns_Provider"] = ("Provider", "Provider"),
        ["Edit_Dns_Prop"] = ("Propagacja (s)", "Propagation (s)"),
        ["Edit_Tip_Prop"] = ("Max czas oczekiwania na TXT w DNS", "Max wait for TXT in DNS"),
        ["Edit_Dns_Hint"] = ("Cloudflare / Route53: rekord TXT _acme-challenge zostanie dodany i usunięty automatycznie. Manual: wartość TXT pojawi się w logu.", "Cloudflare / Route53: the _acme-challenge TXT record is added and removed automatically. Manual: the TXT value appears in the log."),
        ["Edit_Btn_CleanTxt"] = ("Wyczyść stare TXT", "Clean stale TXT"),
        ["Edit_Tip_CleanTxt"] = ("Usuwa osierocone _acme-challenge.* dla domen certyfikatu (tylko CF/Route53)",
            "Deletes orphaned _acme-challenge.* for certificate domains (CF/Route53 only)"),
        ["Edit_Sec_Depl"] = ("WDROŻENIE (DEPLOYMENT)", "DEPLOYMENT"),
        ["Edit_IisSite"] = ("IIS Site Name", "IIS Site Name"),
        ["Edit_ConfigPath"] = ("Config Path", "Config Path"),
        ["Edit_AutoRenew"] = ("Auto odnawianie", "Auto renewal"),
        ["Edit_DaysBefore"] = ("Dni przed wygaśnięciem", "Days before expiry"),
        ["Edit_Recommended"] = ("Zalecane: 30 dni", "Recommended: 30 days"),
        ["Edit_Sec_TasksDepl"] = ("ZADANIA PO WDROŻENIU", "POST-DEPLOYMENT TASKS"),
        ["Edit_Sec_TasksPre"] = ("ZADANIA PRZED WYSTAWIENIEM", "PRE-REQUEST TASKS"),
        ["Edit_Btn_Add"] = ("+ Dodaj", "+ Add"),
        ["Edit_Msg_NameReq"] = ("Nazwa wymagana.", "Name required."),
        ["Edit_Msg_DomainsReq"] = ("Podaj co najmniej jedną domenę.", "Enter at least one domain."),
        ["Edit_Msg_EmailReq"] = ("Podaj poprawny email.", "Enter a valid email."),
        ["Edit_Msg_EabReq"] = ("{0} wymaga EAB Key ID + HMAC.", "{0} requires EAB Key ID + HMAC."),
        ["Edit_Msg_IisSiteReq"] = ("Podaj IIS Site Name", "Enter IIS Site Name"),
        ["Edit_Msg_UrlReq"] = ("Podaj poprawny Directory URL serwera ACME.", "Enter a valid ACME server Directory URL."),
        ["Edit_Msg_CfTokenReq"] = ("Cloudflare wymaga API Token.", "Cloudflare requires an API token."),
        ["Edit_Msg_R53Req"] = ("Route53 wymaga AWS Key ID + Secret.", "Route53 requires AWS Key ID + Secret."),
        ["Edit_Msg_SiteReq"] = ("Wybierz Site IIS.", "Select an IIS site."),
        ["Edit_Iis_Found"] = ("Wykryto: {0}", "Found: {0}"),
        ["Edit_Iis_None"] = ("Brak site'ów: {0}. Nazwę możesz wpisać ręcznie.", "No sites: {0}. You can type the name manually."),
        ["Edit_Msg_NoIisDepl"] = ("Brak deployera IIS.", "No IIS deployer."),
        ["Edit_Msg_BindErr"] = ("Błąd odczytu bindingów: {0}", "Error reading bindings: {0}"),
        ["Edit_Msg_NoBind"] = ("Site '{0}' nie ma hostname bindings (http/https) lub brak uprawnień.\nUruchom jako Administrator i dodaj hostnames w IIS.",
            "Site '{0}' has no hostname bindings (http/https) or missing permissions.\nRun as Administrator and add hostnames in IIS."),
        ["Edit_Msg_Imported"] = ("Pobrano {0} hostnames z '{1}' (dopisano {2} nowych).",
            "Fetched {0} hostnames from '{1}' ({2} new appended)."),
        ["Edit_Msg_SelTask"] = ("Wybierz zadanie", "Select a task"),
        ["Edit_Msg_DelTask"] = ("Usunąć zadanie '{0}'?", "Delete task '{0}'?"),
        ["Edit_Task_NewPre"] = ("Nowe zadanie pre-request", "New pre-request task"),
        ["Edit_Task_NewDepl"] = ("Nowe zadanie deployment", "New deployment task"),
        ["Edit_Msg_NoDomains"] = ("Brak domen.", "No domains."),
        ["Edit_Msg_WebrootTitle"] = ("Wybierz webroot (np. C:\\inetpub\\wwwroot)", "Select webroot (e.g. C:\\inetpub\\wwwroot)"),
        ["Edit_Msg_ConfigTitle"] = ("Wybierz plik vhost/config", "Select vhost/config file"),
        ["Edit_Msg_JanitorErr"] = ("{0}: BŁĄD {1}", "{0}: ERROR {1}"),
        ["Edit_Msg_JanitorOk"] = ("{0}: usunięto {1}", "{0}: deleted {1}"),
        ["Edit_Msg_NoApiProvider"] = ("Brak providera API (Manual?) - nic do czyszczenia.", "No API provider (Manual?) - nothing to clean."),
        ["Edit_Title_Clean"] = ("Czyszczenie TXT", "TXT cleanup"),
        ["Title_Error"] = ("Błąd", "Error"),
        ["App_Msg_AdminRequired"] = ("CertifyApp wymaga uprawnień Administratora (IIS, magazyn certyfikatów komputera, zapis w webroot). Uruchom aplikację ponownie i zatwierdź okno UAC.",
            "CertifyApp requires Administrator rights (IIS, machine certificate store, writing to webroot). Start the app again and accept the UAC prompt."),

        // ---- task edit ----
        ["Win_Task_Title"] = ("Edycja zadania", "Edit task"),
        ["Task_Header_Kicker"] = ("ZADANIE", "TASK"),
        ["Task_Header_Title"] = ("Akcja wykonywana przed wystawieniem lub po wdrożeniu certyfikatu", "Action run before the request or after certificate deployment"),
        ["Task_Name"] = ("Nazwa", "Name"),
        ["Task_Type"] = ("Typ zadania", "Task type"),
        ["Task_Stage"] = ("Etap", "Stage"),
        ["Task_Trigger"] = ("Uruchom", "Run"),
        ["Task_Enabled"] = ("Włączone", "Enabled"),
        ["Task_Params"] = ("PARAMETRY", "PARAMETERS"),
        ["Task_VarsHint"] = ("W argumentach / skryptach możesz użyć: {Name} {PrimaryDomain} {Domains} {CertPath} {PfxPath}.",
            "In arguments / scripts you can use: {Name} {PrimaryDomain} {Domains} {CertPath} {PfxPath}."),
        ["Task_NeverRun"] = ("Jeszcze nie uruchomiony.", "Not run yet."),
        ["Task_LastRun"] = ("Ostatni: {0}", "Last: {0}"),
        ["Task_Msg_NameReq"] = ("Nazwa wymagana.", "Name required."),
        ["Task_Msg_ParamReq"] = ("Parametr '{0}' jest wymagany.", "Parameter '{0}' is required."),
        ["Task_Msg_BadSeconds"] = ("Sekundy muszą być liczbą >= 0.", "Seconds must be a number >= 0."),
        ["TaskType_Export"] = ("Export certyfikatu", "Export certificate"),
        ["TaskType_Restart"] = ("Restart usługi", "Restart service"),
        ["TaskType_Ps"] = ("Skrypt PowerShell", "PowerShell script"),
        ["TaskType_Run"] = ("Uruchom program", "Run program"),
        ["TaskType_Wait"] = ("Czekaj N sekund", "Wait N seconds"),
        ["TaskType_Webhook"] = ("Webhook", "Webhook"),
        ["Trig_OnSuccess"] = ("Po sukcesie", "On success"),
        ["Trig_Always"] = ("Zawsze", "Always"),
        ["Stage_Pre"] = ("Pre-Request", "Pre-Request"),
        ["Stage_Depl"] = ("Deployment", "Deployment"),
        ["Task_On"] = ("Włączony", "Enabled"),
        ["Task_Off"] = ("Wyłączony", "Disabled"),
        ["Task_Last"] = ("Ostatni: {0}", "Last: {0}"),
        ["Task_Never"] = ("Nigdy nie uruchomiony", "Never run"),
        ["Task_Skipped"] = ("Pominięty", "Skipped"),
        ["Param_Format"] = ("Export jako", "Export as"),
        ["Param_Dest"] = ("Ścieżka docelowa", "Destination path"),
        ["Param_Svc"] = ("Nazwa usługi", "Service name"),
        ["Param_Action"] = ("Akcja", "Action"),
        ["Param_Script"] = ("Skrypt .ps1", "Script .ps1"),
        ["Param_Args"] = ("Argumenty", "Arguments"),
        ["Param_Exe"] = ("Program / batch", "Program / batch"),
        ["Param_WorkDir"] = ("Katalog roboczy", "Working directory"),
        ["Param_Seconds"] = ("Sekundy", "Seconds"),
        ["Param_OnStatus"] = ("Wywołaj gdy", "Trigger when"),

        // ---- export ----
        ["Win_Export_Title"] = ("Export certyfikatu", "Export certificate"),
        ["Export_Header_Kicker"] = ("EXPORT CERTYFIKATU", "CERTIFICATE EXPORT"),
        ["Export_Header_Sub"] = ("Wybierz format i miejsce zapisu.", "Choose the format and destination."),
        ["Export_Format"] = ("Export jako", "Export as"),
        ["Export_Dest"] = ("Ścieżka docelowa", "Destination path"),
        ["Export_Hint_Local"] = ("Plik zostanie zapisany lokalnie.", "File will be saved locally."),
        ["Export_Hint_Key"] = ("Uwaga: eksportujesz KLUCZ PRYWATNY - chroń plik.", "Warning: exporting PRIVATE KEY - protect the file."),
        ["Export_Btn_Do"] = ("Eksportuj", "Export"),
        ["Export_Msg_DestReq"] = ("Podaj ścieżkę docelową.", "Enter destination path."),

        // ---- preview ----
        ["Win_Preview_Title"] = ("Podgląd certyfikatu", "Certificate preview"),
        ["Preview_Kicker"] = ("PODGLĄD ŻĄDANIA", "REQUEST PREVIEW"),
        ["Preview_Sub"] = ("Nic nie jest wysyłane do urzędu certyfikacji.", "Nothing is sent to the certificate authority."),
        ["Preview_Sec_Ids"] = ("IDENTYFIKATORY", "IDENTIFIERS"),
        ["Preview_Sec_Ca"] = ("URZĄD I WALIDACJA", "AUTHORITY & VALIDATION"),
        ["Preview_Sec_Depl"] = ("WDROŻENIE I ZADANIA", "DEPLOYMENT & TASKS"),
        ["Preview_Sec_Valid"] = ("WALIDACJA", "VALIDATION"),
        ["Preview_Ok"] = ("✓ Wszystko wygląda dobrze - można robić Request.", "✓ All looks good - you can Request."),
        ["Preview_Footer_Err"] = ("Są błędy - Request prawdopodobnie się nie uda.", "There are errors - Request will likely fail."),
        ["Preview_Footer_Ok"] = ("Gotowy do Request.", "Ready to Request."),
        ["Preview_Primary"] = ("Primary (CN): {0}  |  SAN: {1}  |  Wygasa: {2}", "Primary (CN): {0}  |  SAN: {1}  |  Expires: {2}"),
        ["Preview_Ca"] = ("CA: {0}", "CA: {0}"),
        ["Preview_Ca_Staging"] = ("  [STAGING - test, bez limitów]", "  [STAGING - test, no limits]"),
        ["Preview_Challenge"] = ("Challenge: {0}", "Challenge: {0}"),
        ["Preview_Depl_None"] = ("Deploy: brak (tylko zapis na dysku)", "Deploy: none (save to disk only)"),
        ["Preview_Depl"] = ("Deploy: {0}", "Deploy: {0}"),
        ["Preview_Tasks"] = ("Zadania: {0} pre-request, {1} deployment", "Tasks: {0} pre-request, {1} deployment"),
        ["Preview_Renewal"] = ("Odnawianie: {0}", "Renewal: {0}"),
        ["Preview_Renew_Auto"] = ("Auto, {0} dni przed wygaśnięciem", "Auto, {0} days before expiry"),
        ["Preview_Renew_Manual"] = ("Manual", "Manual"),
        ["Preview_Depl_Iis"] = ("IIS (site: {0})", "IIS (site: {0})"),
        ["Preview_Depl_Apache"] = ("Apache (config: {0})", "Apache (config: {0})"),
        ["Preview_Depl_Nginx"] = ("Nginx (config: {0})", "Nginx (config: {0})"),
        ["Pv_NoDomains"] = ("Brak domen - dodaj co najmniej jedną.", "No domains - add at least one."),
        ["Pv_Wildcard"] = ("Wildcard (*.domena) wymaga challenge dns-01.", "Wildcard (*.domain) requires dns-01 challenge."),
        ["Pv_Email"] = ("Brak poprawnego email dla konta ACME.", "Missing valid email for ACME account."),
        ["Pv_Webroot"] = ("Brak WebRoot dla http-01 - ustaw w edycji.", "Missing WebRoot for http-01 - set it in edit."),
        ["Pv_WebrootDetail"] = ("WebRoot: {0} (plik w .well-known/acme-challenge/)", "WebRoot: {0} (file in .well-known/acme-challenge/)"),
        ["Pv_DnsManual"] = ("Manual: rekord TXT _acme-challenge.<domena> (wartość w Logu przy requeście).",
            "Manual: TXT _acme-challenge.<domain> (value in Log during request)."),
        ["Pv_DnsCf"] = ("Cloudflare auto: utworzy TXT _acme-challenge.*, poczeka na propagację i posprząta.",
            "Cloudflare auto: will create TXT _acme-challenge.*, wait for propagation and clean up."),
        ["Pv_DnsR53"] = ("Route53 auto: utworzy TXT _acme-challenge.*, poczeka na INSYNC i posprząta.",
            "Route53 auto: will create TXT _acme-challenge.*, wait for INSYNC and clean up."),
        ["Pv_Eab"] = ("{0} wymaga EAB Key ID + HMAC.", "{0} requires EAB Key ID + HMAC."),
        ["Pv_EabAuto"] = ("{0}: EAB zostanie pobrany automatycznie dla adresu {1} (ZeroSSL API).",
            "{0}: EAB will be fetched automatically for {1} (ZeroSSL API)."),
        ["Pv_CfToken"] = ("Cloudflare wybrany, ale brak API Token.", "Cloudflare selected, but no API token."),
        ["Pv_R53Creds"] = ("Route53 wybrany, ale brak AWS Key ID + Secret.", "Route53 selected, but no AWS Key ID + Secret."),
        ["Pv_NoTargets"] = ("Brak targetów wdrożenia - certyfikat będzie tylko zapisany na dysku.",
            "No deployment targets - certificate will only be saved to disk."),
        ["Pv_Active"] = ("Certyfikat aktywny (wygasa {0}) - Request wystawi nowy.",
            "Certificate active (expires {0}) - Request will issue a new one."),
        ["Pv_IpOnlyLe"] = ("Identyfikatory IP wspiera tylko Let's Encrypt.", "IP identifiers only support Let's Encrypt."),
        ["Pv_IpInfo"] = ("Adresy IP: walidacja zawsze http-01 (port 80 na tym IP), potrzebny WebRoot.",
            "IP addresses: always http-01 validation (port 80 on that IP), WebRoot required."),

        // ---- alerts ----
        ["Win_Alerts_Title"] = ("Alerty", "Alerts"),
        ["Alerts_Kicker"] = ("DASHBOARD ALERTÓW", "ALERTS DASHBOARD"),
        ["Alerts_Sec_Exp"] = ("WYGASŁE / WYGASAJĄCE", "EXPIRED / EXPIRING"),
        ["Alerts_Sec_Err"] = ("BŁĘDY", "ERRORS"),
        ["Alerts_Sec_Ren"] = ("NADCHODZĄCE ODNOWIENIA (AUTO)", "UPCOMING RENEWALS (AUTO)"),
        ["Alerts_None_Expired"] = ("Brak wygasłych.", "No expired."),
        ["Alerts_None_Expiring"] = ("Brak wygasających (< {0} dni).", "No expiring (< {0} days)."),
        ["Alerts_None_Errors"] = ("Brak błędów.", "No errors."),
        ["Alerts_None_Renewals"] = ("Brak zaplanowanych (tryb Auto + data).", "None scheduled (Auto mode + date)."),
        ["Alerts_None_All"] = ("Brak alertów - wszystko zdrowe.", "No alerts - all healthy."),
        ["Alerts_Sum_Expired"] = ("wygasło: {0}", "expired: {0}"),
        ["Alerts_Sum_Expiring"] = ("wygasa < {0}d: {1}", "expiring < {0}d: {1}"),
        ["Alerts_Sum_Errors"] = ("błędy: {0}", "errors: {0}"),
        ["Alerts_ExpiredAgo"] = ("{0} - wygasł {1} dni temu ({2})", "{0} - expired {1} days ago ({2})"),
        ["Alerts_ExpiringIn"] = ("{0} - za {1} dni ({2})", "{0} - in {1} days ({2})"),
        ["Alerts_RenewalAt"] = ("planowane {0}", "scheduled {0}"),

        // ---- history ----
        ["Win_History_Title"] = ("Historia certyfikatu", "Certificate history"),
        ["History_Kicker"] = ("HISTORIA OPERACJI", "OPERATION HISTORY"),
        ["History_Stats"] = ("Operacje: {0} (OK: {1}, błędy: {2})", "Operations: {0} (OK: {1}, errors: {2})"),
        ["History_Grid"] = ("OPERACJE (OD NAJNOWSZYCH)", "OPERATIONS (NEWEST FIRST)"),
        ["History_Footer"] = ("Przechowywane jest 100 ostatnich wpisów.", "The last 100 entries are kept."),
        ["Hist_Kind_Test"] = ("Staging Test", "Staging Test"),
        ["Hist_Msg_Requested"] = ("Wystawiono i wdrożono", "Issued and deployed"),
        ["Hist_Msg_Deployed"] = ("Wdrożono ręcznie", "Deployed manually"),
        ["Hist_Msg_StagingOk"] = ("Test staging OK", "Staging test OK"),
        ["Hist_Msg_Exported"] = ("{0} -> {1}", "{0} -> {1}"),

        // ---- calendar ----
        ["Win_Cal_Title"] = ("Kalendarz odnowień", "Renewal calendar"),
        ["Cal_Today"] = ("Dziś", "Today"),
        ["Cal_Legend_Ren"] = ("Odnowienie", "Renewal"),
        ["Cal_Legend_Exp"] = ("Wygasa", "Expires"),
        ["Cal_Footer"] = ("Wpisów w miesiącu: {0}", "Entries this month: {0}"),
        ["Cal_Dow"] = ("Pn;Wt;Śr;Cz;Pt;Sb;Nd", "Mon;Tue;Wed;Thu;Fri;Sat;Sun"),

        // ---- settings ----
        ["Win_Settings_Title"] = ("Ustawienia", "Settings"),
        ["Settings_Sec_General"] = ("OGÓLNE", "GENERAL"),
        ["Settings_Sec_Email"] = ("POWIADOMIENIA E-MAIL (SMTP)", "E-MAIL NOTIFICATIONS (SMTP)"),
        ["Settings_Header"] = ("Ustawienia", "Settings"),
        ["Settings_Header_Sub"] = ("Język interfejsu i powiadomienia e-mail.", "Interface language and e-mail notifications."),
        ["Settings_Enable"] = ("Wysyłaj powiadomienia e-mail", "Send e-mail notifications"),
        ["Settings_Host"] = ("Serwer SMTP", "SMTP server"),
        ["Settings_Port"] = ("Port", "Port"),
        ["Settings_User"] = ("Użytkownik", "Username"),
        ["Settings_Pass"] = ("Hasło", "Password"),
        ["Settings_From"] = ("Od (From)", "From"),
        ["Settings_To"] = ("Do (To)", "To"),
        ["Settings_Tip_To"] = ("Odbiorcy rozdzieleni ; lub ,", "Recipients separated by ; or ,"),
        ["Settings_WarnDays"] = ("Ostrzegaj (dni)", "Warn (days)"),
        ["Settings_Tip_Warn"] = ("Wygasające wcześniej niż X dni trafia do digesta", "Expiring sooner than X days goes to digest"),
        ["Settings_Btn_Test"] = ("Wyślij test", "Send test"),
        ["Settings_TestSubject"] = ("[CertifyApp] Test powiadomień", "[CertifyApp] Notification test"),
        ["Settings_TestBody"] = ("Test z CertifyApp ({0}). Powiadomienia działają.", "Test from CertifyApp ({0}). Notifications work."),
        ["Settings_Hint_Gmail"] = ("Gmail: użyj hasła aplikacji. Hasło SMTP jest zapisywane jawnym tekstem w appsettings.json.", "Gmail: use an app password. The SMTP password is stored in plain text in appsettings.json."),
        ["Settings_Footer"] = ("Zapis: %ProgramData%\\CertifyApp\\appsettings.json", "Saved to: %ProgramData%\\CertifyApp\\appsettings.json"),
        ["Settings_Lang"] = ("Język", "Language"),
        ["Settings_Tip_Lang"] = ("Auto = język systemu", "Auto = system language"),
        ["Settings_Lang_Auto"] = ("Automatycznie (system)", "Automatic (system)"),
        ["Settings_Sending"] = ("Wysyłam...", "Sending..."),
        ["Settings_TestOk"] = ("Test wysłany - sprawdź skrzynkę.", "Test sent - check mailbox."),
        ["Settings_TestErr"] = ("BŁĄD: {0}", "ERROR: {0}"),
        ["Cfg_Err_Host"] = ("Brak SmtpHost.", "Missing SmtpHost."),
        ["Cfg_Err_Port"] = ("Zły SmtpPort.", "Bad SmtpPort."),
        ["Cfg_Err_From"] = ("Zły EmailFrom.", "Bad EmailFrom."),
        ["Cfg_Err_To"] = ("Brak odbiorców (EmailTo).", "No recipients (EmailTo)."),

        // ---- import ----
        ["Win_Import_Title"] = ("Import backupu", "Import backup"),
        ["Import_Kicker"] = ("IMPORT BACKUPU", "IMPORT BACKUP"),
        ["Import_Contents"] = ("ZAWARTOŚĆ PACZKI", "PACKAGE CONTENTS"),
        ["Import_Mode"] = ("TRYB", "MODE"),
        ["Import_Secrets"] = ("Ścieżki plików zostaną przepisane na ten komputer. Paczka zawiera sekrety (klucze, tokeny).",
            "File paths will be remapped to this machine. Package contains secrets (keys, tokens)."),
        ["Import_Btn_Do"] = ("Importuj", "Import"),
        ["Import_Mode_Merge"] = ("Połącz (dodaj nowe)", "Merge (add new)"),
        ["Import_Mode_MergeHint"] = ("Doda brakujące certyfikaty (po Id). Istniejące, ustawienia lokalne bez zmian.",
            "Adds missing certificates (by Id). Existing ones and local settings unchanged."),
        ["Import_Mode_Replace"] = ("Zamień wszystko", "Replace all"),
        ["Import_Mode_ReplaceHint"] = ("Usuwa lokalne certyfikaty i wstawia z paczki (też appsettings i konta).",
            "Deletes local certificates and inserts from package (also appsettings and accounts)."),
        ["Import_Manifest"] = ("Certyfikaty: {0}\nWyeksportowano: {1} (maszyna: {2})\nKonta ACME: {3}  |  Ustawienia: {4}",
            "Certificates: {0}\nExported: {1} (machine: {2})\nACME accounts: {3}  |  Settings: {4}"),
        ["YesNo_Yes"] = ("tak", "yes"),
        ["YesNo_No"] = ("nie", "no"),

        // ---- windows service ----
        ["Win_Service_Title"] = ("Usługa Windows", "Windows service"),
        ["Svc_Kicker"] = ("USŁUGA ODNAWIANIA W TLE", "BACKGROUND RENEWAL SERVICE"),
        ["Svc_Intro"] = ("Odnawia certyfikaty z włączonym auto odnawianiem także przy zamkniętej aplikacji i bez zalogowanego użytkownika. Log: logs\\service-<data>.txt.", "Renews certificates with auto renewal enabled even while the app is closed and no user is signed in. Log: logs\\service-<date>.txt."),
        ["Svc_Row_Status"] = ("Status:", "Status:"),
        ["Svc_Row_Name"] = ("Nazwa:", "Name:"),
        ["Svc_Row_Dir"] = ("Katalog:", "Directory:"),
        ["Svc_Row_Files"] = ("Pliki:", "Files:"),
        ["Svc_Status_NotInstalled"] = ("Niezainstalowana", "Not installed"),
        ["Svc_Status_Running"] = ("Działa", "Running"),
        ["Svc_Status_Stopped"] = ("Zatrzymana", "Stopped"),
        ["Svc_Status_Pending"] = ("Zmienia stan ({0})", "Changing state ({0})"),
        ["Svc_Files_Current"] = ("Aktualne (zgodne z aplikacją)", "Up to date (match the app)"),
        ["Svc_Files_Outdated"] = ("Inne niż w aplikacji - kliknij Aktualizuj", "Differ from the app - click Update"),
        ["Svc_Btn_Install"] = ("Zainstaluj", "Install"),
        ["Svc_Btn_Update"] = ("Aktualizuj", "Update"),
        ["Svc_Btn_Start"] = ("Uruchom", "Start"),
        ["Svc_Btn_Stop"] = ("Zatrzymaj", "Stop"),
        ["Svc_Btn_Uninstall"] = ("Odinstaluj", "Uninstall"),
        ["Svc_Msg_UninstallConfirm"] = ("Odinstalować usługę? Odnawianie w tle będzie działać tylko przy otwartej aplikacji.",
            "Uninstall the service? Background renewal will only run while the app is open."),

        // ---- password ----
        ["Win_Pw_Title"] = ("Hasło backupu", "Backup password"),
        ["Pw_Kicker"] = ("HASŁO BACKUPU (AES-256-GCM)", "BACKUP PASSWORD (AES-256-GCM)"),
        ["Pw_Pass"] = ("Hasło", "Password"),
        ["Pw_Repeat"] = ("Powtórz", "Repeat"),
        ["Pw_Footer"] = ("Min 8 znaków. Bez hasła nie odszyfrujesz.", "Min 8 chars. Without password you cannot decrypt."),
        ["Pw_Err_Required"] = ("Podaj hasło.", "Enter password."),
        ["Pw_Err_Min"] = ("Hasło min 8 znaków.", "Password min 8 chars."),
        ["Pw_Err_Match"] = ("Hasła się różnią.", "Passwords differ."),
        ["Bk_Err_BadPass"] = ("Złe hasło lub uszkodzony plik.", "Wrong password or corrupt file."),
        ["Bk_Err_NotEncrypted"] = ("To nie jest szyfrowany backup (.cbak).", "Not an encrypted backup (.cbak)."),
        ["Bk_Err_NoManifest"] = ("Brak manifestu - to nie jest backup CertifyApp.", "No manifest - not a CertifyApp backup."),
        ["Bk_Err_BadManifest"] = ("Uszkodzony manifest.", "Corrupt manifest."),
        ["Bk_Err_Version"] = ("Nieznana wersja backupu: {0}.", "Unknown backup version: {0}."),
        ["Bk_Err_NoCerts"] = ("Brak managed_certificates.json w paczce.", "No managed_certificates.json in package."),
        ["Bk_Err_Encrypted"] = ("Backup szyfrowany - podaj hasło.", "Encrypted backup - enter password."),
        ["Bk_Msg_Exported"] = ("Certyfikaty: {0}", "Certificates: {0}"),
        ["Bk_Msg_ExportedEnc"] = ("Certyfikaty: {0} (szyfrowany)", "Certificates: {0} (encrypted)"),
        ["Bk_Msg_Imported"] = ("Zaimportowano: {0}, pominięto: {1}, brakujące pliki: {2}",
            "Imported: {0}, skipped: {1}, missing files: {2}"),

        // ---- exporter ----
        ["Exp_Err_NoCert"] = ("Brak wystawionego certyfikatu (CertPath) - najpierw Request.",
            "No issued certificate (CertPath) - Request first."),
        ["Exp_Err_NoDest"] = ("Nie podano ścieżki docelowej.", "No destination path."),
        ["Exp_Err_NoKey"] = ("Brak klucza prywatnego (KeyPath).", "No private key (KeyPath)."),
        ["Exp_Err_NoPfx"] = ("Brak pliku PFX - najpierw Request.", "No PFX file - Request first."),
        ["Exp_Err_NoChain"] = ("Nie udało się wyodrębnić łańcucha z chain.pem.", "Could not extract chain from chain.pem."),
        ["Exp_Err_ChainFile"] = ("Brak pliku chain.pem - najpierw Request.", "No chain.pem - Request first."),
        ["Exp_Err_Format"] = ("Nieobsługiwany format: {0}", "Unsupported format: {0}"),

        // ---- tasks runner ----
        ["Task_Err_Dest"] = ("Brak DestinationPath.", "Missing DestinationPath."),
        ["Task_Err_Format"] = ("Nieznany format: {0}", "Unknown format: {0}"),
        ["Task_Err_Exe"] = ("Brak programu: {0}", "Missing program: {0}"),
        ["Task_Err_ExeMissing"] = ("Brak programu.", "Missing program."),
        ["Task_Err_NoStart"] = ("Nie można uruchomić: {0}", "Cannot start: {0}"),
        ["Task_Err_Svc"] = ("Brak ServiceName.", "Missing ServiceName."),
        ["Task_Err_Script"] = ("Brak skryptu: {0}", "Missing script: {0}"),
        ["Task_Err_Seconds"] = ("Nieprawidłowe Seconds.", "Invalid Seconds."),
        ["Task_Err_Url"] = ("Brak Url.", "Missing Url."),
        ["Task_Err_Type"] = ("Nieznany typ zadania: {0}", "Unknown task type: {0}"),
        ["Task_Msg_Done"] = ("Zadanie zakończone pomyślnie", "Task completed successfully"),

        // ---- renewal / email ----
        ["Renew_Msg_PreFail"] = ("Pre-Request task nie powiódł się - pomijam.", "Pre-Request task failed - skipping."),
        ["Renew_Msg_Renewed"] = ("Odnowiono pomyślnie ", "Renewed successfully "),
        ["Status_Renewed"] = ("Odnowiono", "Renewed"),
        ["Status_Issued"] = ("Wystawiono", "Issued"),
        ["Deploy_Msg_Failed"] = ("Certyfikat wystawiony, ale wdrożenie nie powiodło się: {0}", "Certificate issued, but deployment failed: {0}"),
        ["Mail_Subject"] = ("[CertifyApp] Odnowienia: {0} OK, {1} błędów{2}", "[CertifyApp] Renewals: {0} OK, {1} errors{2}"),
        ["Mail_Subject_Exp"] = (", {0} wygasa", ", {0} expiring"),
        ["Mail_Body_Header"] = ("CertifyApp - raport {0}", "CertifyApp - report {0}"),
        ["Mail_Body_Summary"] = ("Przetworzone: {0} (OK: {1}, błędy: {2})", "Processed: {0} (OK: {1}, errors: {2})"),
        ["Mail_Row_Fail"] = ("BLAD", "ERROR"),
        ["Mail_Body_ExpHeader"] = ("Wygasają w < {0} dni:", "Expiring in < {0} days:"),
        ["Mail_Body_ExpRow"] = ("  ! {0} ({1}) - {2} (za {3} dni)", "  ! {0} ({1}) - {2} (in {3} days)"),
        ["Mail_Body_ExpDate"] = ("       Wygasa: {0}", "       Expires: {0}"),
        ["Mail_Fail_Subject"] = ("[CertifyApp] BŁĄD certyfikatu {0}", "[CertifyApp] Certificate ERROR {0}"),
        ["Mail_Fail_Body"] = ("Certyfikat: {0} ({1})\nCzas: {2}\nBłąd: {3}\n", "Certificate: {0} ({1})\nTime: {2}\nError: {3}\n"),

        // ---- ACME errors (StatusMessage) ----
        ["Acme_Err_Eab"] = ("{0} wymaga EAB (External Account Binding). Uzupełnij EAB Key ID + HMAC w edycji certyfikatu.",
            "{0} requires EAB (External Account Binding). Fill EAB Key ID + HMAC in certificate edit."),
        ["Acme_Err_WebrootAccess"] = ("Brak uprawnień do zapisu w webroot {0}. {1}Uruchom CertifyApp jako Administrator albo nadaj prawo zapisu: icacls \"{0}\" /grant \"{2}:(OI)(CI)M\"",
            "No write permission to webroot {0}. {1}Run CertifyApp as Administrator or grant write access: icacls \"{0}\" /grant \"{2}:(OI)(CI)M\""),
        ["Acme_Hint_NotElevated"] = ("Aplikacja działa bez uprawnień Administratora. ", "The app is running without Administrator rights. "),
        ["Acme_Err_ZeroSslEab"] = ("ZeroSSL: nie udało się pobrać EAB dla {0}: {1}. Wpisz EAB ręcznie (panel ZeroSSL > Developer).",
            "ZeroSSL: could not fetch EAB for {0}: {1}. Enter EAB manually (ZeroSSL dashboard > Developer)."),
        ["Acme_Err_NoDomains"] = ("Brak domen do certyfikatu.", "No domains for certificate."),
        ["Acme_Err_NoEmail"] = ("Brak adresu email dla konta ACME.", "Missing email for ACME account."),
        ["Acme_Err_NoChallenge"] = ("Nie udało się pobrać challenge dla {0}", "Could not get challenge for {0}"),
        ["Acme_Err_VerifyFail"] = ("Weryfikacja {0} nieudana: {1}", "Verification failed for {0}: {1}"),
        ["Acme_Err_ValTimeout"] = ("Timeout walidacji {0}", "Validation timeout {0}"),
        ["Acme_Err_OrderInvalid"] = ("Order invalid: {0}", "Order invalid: {0}"),
        ["Acme_Err_OrderTimeout"] = ("Timeout order finalize", "Order finalize timeout"),
        ["Acme_Err_NoWebroot"] = ("Brak skonfigurowanej ścieżki webroot dla domeny {0}. Ustaw ChallengeConfig.HttpChallengeRoot lub mapę domen.",
            "No webroot configured for domain {0}. Set ChallengeConfig.HttpChallengeRoot or domain map."),
        ["Acme_Err_IpOnlyLe"] = ("Identyfikatory IP wspiera tylko Let's Encrypt (jest: {0}).",
            "IP identifiers only support Let's Encrypt (is: {0})."),
        ["Acme_Err_IpWebroot"] = ("IP {0} wymaga http-01 z WebRoot (dns-01 niedozwolone dla IP). Ustaw WebRoot w edycji.",
            "IP {0} requires http-01 with WebRoot (dns-01 not allowed for IP). Set WebRoot in edit."),
        ["Acme_Err_NoLocation"] = ("Brak Location konta.", "No account Location."),
        ["Acme_Err_NoOrderLocation"] = ("Brak Location orderu.", "No order Location."),
        ["Acme_Err_EmptyChain"] = ("Pusty łańcuch z CA.", "Empty chain from CA."),
        ["Acme_Err_NoChallengeInAuthz"] = ("Brak challenge {0} w autoryzacji.", "No {0} challenge in authorization."),
        ["Acme_Err_PollTimeout"] = ("Timeout: {0}", "Timeout: {0}"),
        ["Acme_Err_BadStatus"] = ("{0} -> {1}", "{0} -> {1}"),
        ["Acme_Err_NoZone"] = ("Cloudflare: brak strefy dla {0} (token musi mieć Zone Read).",
            "Cloudflare: no zone for {0} (token needs Zone Read)."),
        ["Acme_Err_NoZoneR53"] = ("Route53: brak publicznej strefy dla {0}.", "Route53: no public zone for {0}."),
        ["Acme_Err_NoRecordId"] = ("Cloudflare: brak id rekordu w odpowiedzi.", "Cloudflare: no record id in response."),
        ["Acme_Err_NoChangeId"] = ("Route53: brak Change Id w odpowiedzi.", "Route53: no Change Id in response."),
    };
}
