<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyVersion>26.10.5.1</AssemblyVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Localization\Translations\*.json" LogicalName="Certify.Core.Localization.Translations.%(Filename).json" WithCulture="false" />
  </ItemGroup>

</Project>
